# ==============================================================================
# Mathigon Studio Default Settings
# (c) Mathigon
# ==============================================================================


siteName: KhaBoom Learning
description: Interactive learning platform
domain: khaboom.onrender.com

privacyURL: /policies
banner: © KhaBoom Learning, 2025
locales: [en, es, fr]

contentDir: "mycourses"

search:
  enabled: true

sitemap: []

header:
  logo: images/logo.svg
  title: KhaBoom Learning
  links:
    - title: Courses
      icon: library
      url: /courses

social: {}

footer:
  rows:
    - links:
        - title: About
          url: /about
        - title: Courses
          url: /courses
  copyright: © KhaBoom Learning, 2025

courses:
  revealAll: true
  audio: false

accounts:
  enabled: true
  minAge: 13
  privacyPolicy: /policies
  termsOfUse: /policies

tutor:
  enabled: true
  name: Tutor
  icon: images/archie.svg
