# ==============================================================================
# Mathigon Studio Default Settings
# (c) Mathigon
# ==============================================================================


siteName: KhaBoom
description: Interactive learning platform
domain: khaboom.onrender.com

privacyURL: /policies
banner: (c) KhaBoom Ltd
locales: [en, es, fr]

contentDir: "mycourses"

search:
  enabled: true

sitemap: []

header:
  logo: images/KhaBoom.png
  title: KhaBoom.jpg
  links:
    - title: Courses
      icon: library
      url: /courses

social: {}

footer:
  rows:
    - links:
        - title: About
          url: /about
        - title: Courses
          url: /courses
  copyright: © KhaBoom, 2025

courses:
  revealAll: true
  audio: false

accounts:
  enabled: true
  minAge: 13
  privacyPolicy: /policies
  termsOfUse: /policies
  mongoServer: mongodb+srv://joinquit:31102004@kbcluster.wok68pc.mongodb.net/?retryWrites=true&w=majority&appName=KBCluster

tutor:
  enabled: true
  name: Tutor
  icon: images/archie.svg
